name: Rust

on:
    push:
        branches: ['master', 'develop']
    pull_request:
        branches: ['master', 'develop']

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Install cargo-llvm-cov
              uses: taiki-e/install-action@cargo-llvm-cov
            - name: Build
              run: cargo build --verbose
            - name: Run tests
              run: cargo llvm-cov --lcov --output-path coverage.lcov --verbose
            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v3
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
